In [1]:
import numpy as np

In [2]:
## Определим разные полезные функции

def sigmoid(x):
    """сигмоидальная функция, работает и с числами, и с векторами (поэлементно)"""
    return 1 / (1 + np.exp(-x))

def sigmoid_prime(x):
    """производная сигмоидальной функции, работает и с числами, и с векторами (поэлементно)"""
    return sigmoid(x) * (1 - sigmoid(x))

In [57]:
class NBase_2():
    def __init__(self, W, b1, U, b2,
                 reg=0.001, alpha=0.01):

        # Set regularization
        self.lreg = float(reg)
        self.alpha = alpha # default training rate

        self.W = np.array(W)
        self.b1 = b1
        self.U = np.array(U)
        self.b2 = b2
        
        self.grads_U = 0.0
        self.grads_b2 = 0.0
        self.grads_W = 0.0
        self.grads_b1 = 0.0

    def _acc_grads(self, input_x, true_label):
        
        # Forward propagation
        a1 = np.array(input_x).reshape(len(input_x), 1)
        z2 = self.W.dot(a1) + self.b1
        a2 = sigmoid(z2) 
        z3 = self.U.dot(a2) + self.b2
        y_hat = sigmoid(z3)

        y = true_label
        delta3 = y_hat - y
        ##
        # Backpropagation
        # dJ/dU
        self.grads_U += np.outer(delta3, a2) + self.lreg * self.U
        # dJ/db2
        self.grads_b2 += delta3
        delta2 = self.U.T.dot(delta3) * sigmoid_prime(z2)
        # dJ/dW @TODO: check
        self.grads_W += np.outer(delta2, a1) + self.lreg * self.W
        # dJ/db1
        self.grads_b1 += delta2


    def predict_proba(self, input_x):
        a1 = input_x
        z2 = self.W.dot(a1) + self.b1
        a2 = sigmoid(z2) 
        z3 = self.U.dot(a2) + self.b2
        y_hat = sigmoid(z3)

        return y_hat


    def predict(self, input_x):
        return argmax(self.predict_proba(windows), axis=1)

In [63]:
W = [[2.0,2.0, 2.0], [2.0, 2.0, 2.0]]
b1 = 0.0
U = [[1.0, 1.0]]
b2 = 0.0
reg = 0.0

In [64]:
nn = NBase_2(W,b1,U,b2,reg)

In [65]:
nn._acc_grads([0, 1, 2], 1)

In [66]:
nn.grads_W

array([[ 0.       , -0.0002953, -0.0005906],
       [ 0.       , -0.0002953, -0.0005906]])

In [67]:
W = [[8.0,7.0, 8.0], [10.0, 10.0, 9.0]]
b1 = 0.0
U = [[10.0, 9.0]]
b2 = 0.0
reg = 0.0

In [68]:
nn = NBase_2(W,b1,U,b2,reg)

In [69]:
nn._acc_grads([0, 1, 2], 1)

In [70]:
nn.grads_W

array([[  0.00000000e+00,  -5.74952261e-18,  -1.14990452e-17],
       [  0.00000000e+00,  -3.48663261e-20,  -6.97326522e-20]])

In [71]:
W = [[0.2,0.9, 0.6], [0.2, 0.3, 0.7]]
b1 = 0.0
U = [[0.2, 0.5]]
b2 = 0.0
reg = 0.0

In [72]:
nn = NBase_2(W,b1,U,b2,reg)

In [73]:
nn._acc_grads([15.0, 5.0, 15.0], 1)

In [74]:
nn.grads_W

array([[ -6.79445581e-08,  -2.26481860e-08,  -6.79445581e-08],
       [ -7.61265598e-07,  -2.53755199e-07,  -7.61265598e-07]])

In [40]:
class NBase_2_strange():
    def __init__(self, W, U):
        self.W = np.array(W)
        self.U = np.array(U)
        
        self.grads_U = 0.0
        self.grads_W = 0.0

    def _acc_grads(self, input_x, true_label):
        
        # Forward propagation
        a1 = np.array(input_x).reshape(len(input_x), 1)
        z2 = self.W.dot(a1)
        a2 = sigmoid(z2)
        a2[0,] = np.max(z2[0,])
        z3 = self.U.dot(a2)
        y_hat = sigmoid(z3)
        
        print ("a1")
        print (a1)
        
        print ("z2")
        print (z2)
        
        print ("a2")
        print (a2)
        
        print ("z3")
        print (z3)
        
        print ("y_hat")
        print (y_hat)

        y = true_label
        delta3 = (y_hat - y) * sigmoid_prime(z3)
        
        print ("delta3")
        print (delta3)
        ##
        # Backpropagation
        # dJ/dU
        self.grads_U += np.outer(delta3, a2)
        # dJ/db2
        new_grad = np.array([1.0, sigmoid_prime(z2[1,0])]).reshape(2, 1)
        print (new_grad.shape)
        print (sigmoid_prime(z2).shape)
        delta2 = self.U.T.dot(delta3) * new_grad
        # dJ/dW
        self.grads_W += np.outer(delta2, a1)
        
        print ("grads_U")
        print (self.grads_U)
        
        print ("new_grad")
        print (new_grad)
        
        print ("delta2")
        print (delta2)
        
        print ("grads_W")
        print (self.grads_W)

In [41]:
W = [[0.7,0.2, 0.7], [0.8, 0.3, 0.6]]
U = [[0.2, 0.4]]

In [42]:
nn = NBase_2_strange(W,U)

In [43]:
nn._acc_grads([0.0, 1.0, 1.0], 1)

a1
[[ 0.]
 [ 1.]
 [ 1.]]
z2
[[ 0.9]
 [ 0.9]]
a2
[[ 0.9      ]
 [ 0.7109495]]
z3
[[ 0.4643798]]
y_hat
[[ 0.61405267]]
delta3
[[-0.09146642]]
(2,)
(2, 1)
grads_U
[[-0.08231978 -0.06502801]]
new_grad
[ 1.          0.20550031]
delta2
[[-0.01829328 -0.00375928]
 [-0.03658657 -0.00751855]]
grads_W
[[ 0.         -0.01829328 -0.01829328]
 [ 0.         -0.00375928 -0.00375928]
 [ 0.         -0.03658657 -0.03658657]
 [ 0.         -0.00751855 -0.00751855]]


In [55]:
nn.U.T * (-0.38594733)

array([[-0.07718947],
       [-0.15437893]])

In [72]:
sigmoid_prime(0.9)*((0.38594733) ** 2)

0.030610368465535307